const express = require('express');
const router = express.Router();
const {Octokit} = require('@octokit/rest');

router.post('/create-pr', async(req, res) => {
  const {githubToken, owner, repo, filePath, fixedCode, issueTitle} = req.body;

  if(!githubToken || !owner || !repo || !filePath || !fixedCode) {
    return res.status(400).json({error: 'Missing required Compilation parameters.'});
  }

  const octokit = new Octokit({auth: githubToken});

  try {
    const {data : userProfile} = await octokit.rest.users.getAuthenticated();
    const userGithubName = userProfile.login;

    console.log(`Forking ${owner}/${repo} into ${userGithubName}/${repo}...`);
    await octokit.rest.repos.createFork({owner, repo});

    const branchName = `devFlow-fix-${Date.now().toString().slice(-6)}`;

    const {data: repoInfo} = await octokit.rest.repos.get({owner, repo});

    const defaultBranch = repoInfo.default_branch;

    const {data: refData} = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`
    });

    const baseSha = refData.object.sha;

    await new Promise(resolve => setTimeout(resolve, 5000));

    await octokit.rest.git.createRef({
      owner: userGithubName,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha
    })

    const {data: fileData} = await octokit.rest.repos.getContent({
      owner: userGithubName,
      repo,
      path: filePath,
      ref: branchName
    })

    await octokit.rest.repos.createOrUpdateFileContents({
      owner: userGithubName,
      repo,
      path: filePath,
      message: `Fix: Auto patch for ${issueTitle} via Devflow AI`,
      content: Buffer.from(fixedCode).toString('base64'),
      sha: fileData.sha,
      branch: branchName
    })

    const prResponse = await octokit.rest.pulls.create({
      owner,
      repo,
      title: `Devflow AI fix for: ${issueTitle}`,
      head: `${userGithubName}:${branchName}`,
      base: defaultBranch,
      body: `### 🤖 Automated Patch Generated by DevFlow AI\n\nThis PR addresses the issue: **${issueTitle}**.\n\nFile modified: \`${filePath}\`.\n\nPlease review the syntax verification layers before merging.`
    })
    res.status(201).json({ 
        message: "Pull Request deployed successfully!", 
        prUrl: prResponse.data.html_url 
    });
  }
  catch (err) {
    console.error("PR Engine Failure Detailed Stack:", err);
    res.status(500).json({ 
        error: err.message || "Engine compilation error processing GitHub automation pipeline." 
    });
  }
})

module.exports = router;
